name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Iniciar sesión en GHCR
      run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Construir la imagen Docker
      run: |
        docker build -f Front/Dockerfile -t ghcr.io/${{ github.repository_owner }}/my-image-name:latest Front


    - name: Subir la imagen a GHCR
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/my-image-name:latest
